name: Release

on:
  push:
    tags: [v*]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: pnpm i --frozen-lockfile

      - name: Prebuild
        run: pnpm run build

      - name: Publish to NPM
        run: npm publish --provenance
